services:
  - type: web
    name: subtitle-ai-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: subtitle-ai-frontend
    env: static
    buildCommand: |
      echo "Building frontend..."
      # You can add build steps here if using React/Vue later
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
